name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: 
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: fuujiro/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 4d3a2f446e5ba67e08ed3f02efd9a6e8
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
